# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ob-pattern-2.resource.prefix" . }}-ob-am-conf-jaggeryapp-devportal
  namespace : {{ .Release.Namespace }}
data:
  settings-berlin.js: |-
    const Settings = {
        app: {
            context: '/devportal',
            customUrl: {
                enabled: false,
                forwardedHeader: 'X-Forwarded-For',
            },
            origin: {
                host: 'localhost',
            },
            subscriptionLimit: 1000,
            singleLogout: {
                enabled: true, // If enabled, user will be logged out from the App when logged out from the IDP (eg: SSO logout from a different App).
                timeout: 4000, // Defines the timeout for the above periodical session status check
            },
        },
        grantTypes: {
            authorization_code: 'Code',
            implicit: 'Implicit',
            refresh_token: 'Refresh Token',
            password: 'Password',
            'iwa:ntlm': 'IWA-NTLM',
            client_credentials: 'Client Credentials',
            'urn:ietf:params:oauth:grant-type:saml2-bearer': 'SAML2',
            'urn:ietf:params:oauth:grant-type:jwt-bearer': 'JWT',
            kerberos: 'Kerberos',
            'urn:ietf:params:oauth:grant-type:device_code': 'Device Code',
        },
        openbanking: {
            spec: 'BERLIN',
            grantTypes: {
                authorization_code: 'Code',
                implicit: 'Implicit',
                refresh_token: 'Refresh Token',
                client_credentials: 'Client Credentials',
            },
        },
    };

  settings-uk.js: |-
    const Settings = {
        app: {
            context: '/devportal',
            customUrl: {
                enabled: false,
                forwardedHeader: 'X-Forwarded-For',
            },
            origin: {
                host: 'localhost',
            },
            subscriptionLimit: 1000,
            singleLogout: {
                enabled: true, // If enabled, user will be logged out from the App when logged out from the IDP (eg: SSO logout from a different App).
                timeout: 4000, // Defines the timeout for the above periodical session status check
            },
        },
        grantTypes: {
            authorization_code: 'Code',
            implicit: 'Implicit',
            refresh_token: 'Refresh Token',
            password: 'Password',
            'iwa:ntlm': 'IWA-NTLM',
            client_credentials: 'Client Credentials',
            'urn:ietf:params:oauth:grant-type:saml2-bearer': 'SAML2',
            'urn:ietf:params:oauth:grant-type:jwt-bearer': 'JWT',
            kerberos: 'Kerberos',
            'urn:ietf:params:oauth:grant-type:device_code': 'Device Code',
        },
        openbanking: {
            spec: 'UK',
            grantTypes: {
                authorization_code: 'Code',
                implicit: 'Implicit',
                refresh_token: 'Refresh Token',
                client_credentials: 'Client Credentials',
            },
        },
    };
